name: Build and deploy Node.js app - Staging

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # PASO CLAVE: Entrar a la carpeta src/api para instalar y compilar
      - name: npm install and build
        run: |
          cd src/api
          npm install
          npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: src/api # Solo subimos la carpeta del backend ya compilada

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: ./api-build # Lo descargamos en una carpeta limpia

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-orderhub-api-eespinosa'
          slot-name: 'staging'
          package: ./api-build # Desplegamos lo que descargamos
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_STAGING }}